#!/bin/sh
uci batch <<-EOF
    # mesh
    set wireless.wifi_ninux='wifi-iface'
    set wireless.wifi_ninux.device=radio0
    set wireless.wifi_ninux.ifname=ninux
    set wireless.wifi_ninux.encryption=none
    set wireless.wifi_ninux.mode=adhoc
    set wireless.wifi_ninux.network=ninux
    set wireless.wifi_ninux.ssid=ninux.org
    # access point
    set wireless.wifi_wlan0='wifi-iface'
    set wireless.wifi_wlan0.device=radio0
    set wireless.wifi_wlan0.ifname=wlan0
    set wireless.wifi_wlan0.encryption=none
    set wireless.wifi_wlan0.mode=ap
    set wireless.wifi_wlan0.network=lan
    set wireless.wifi_wlan0.ssid=www.ninux.org-palermo
    # enable radio0 if present
    radio0=$(uci get wireless.radio0)
    if [ "$radio0" == "wifi-device" ]; then
        uci set wireless.radio0.disabled=0
    fi
    # enable radio1 if present
    radio1=$(uci get wireless.radio1)
    if [ "$radio1" == "wifi-device" ]; then
        uci set wireless.radio1.disabled=0
    fi
    # commit
    commit wireless
EOF
exit 0
